version: "3"
services:
    rust:
        image: alfred456654/jupyterlab-rust:latest
        ports:
            - "8888:8888"
        volumes:
            - "./notebooks:/jupyter/notebooks"
        environment:
            - GRANT_SUDO=yes
